//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Rusanova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ТурфирмаEntities : DbContext
    {
        public ТурфирмаEntities()
            : base("name=ТурфирмаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ведомость_продажей> Ведомость_продажей { get; set; }
        public virtual DbSet<Гостиницы> Гостиницы { get; set; }
        public virtual DbSet<Состав_групп> Состав_групп { get; set; }
        public virtual DbSet<Туристическая_группа> Туристическая_группа { get; set; }
        public virtual DbSet<Туристы> Туристы { get; set; }
        public virtual DbSet<Туры> Туры { get; set; }
    }
}
