//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Rusanova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомость_продажей
    {
        public int Код_ведомости { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public int Код_группы { get; set; }
        public int Код_гостиницы { get; set; }
        public Nullable<decimal> Общая_стоимость { get; set; }
    
        public virtual Гостиницы Гостиницы { get; set; }
        public virtual Туристическая_группа Туристическая_группа { get; set; }
    }
}
