//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Rusanova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Туры()
        {
            this.Состав_групп = new HashSet<Состав_групп>();
        }
    
        public int Код_тура { get; set; }
        public string Название { get; set; }
        public Nullable<System.DateTime> Дата_отправления { get; set; }
        public Nullable<System.DateTime> Дата_прибытия { get; set; }
        public string Телефон_турагента { get; set; }
        public string Страна { get; set; }
        public string Города { get; set; }
        public Nullable<int> Количество_туристов { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_групп> Состав_групп { get; set; }
    }
}
