//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Rusanova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туристы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Туристы()
        {
            this.Состав_групп = new HashSet<Состав_групп>();
        }
    
        public int Код_туриста { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Паспортные_данные { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Пол { get; set; }
        public Nullable<int> Возраст { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_групп> Состав_групп { get; set; }
    }
}
